### ISSUE TITLE
QSP-1 Self Destruction of Main Upgradeable Module

### ISSUE THREAD

**Issue by Agusx1211** [arcadeum/wallet-contracts#62]
<img width="1498" alt="Screenshot 2020-06-08 at 12 24 21" src="https://user-images.githubusercontent.com/12701942/84020363-fcc78c00-a982-11ea-84ed-932ceaa8ef9a.png">

**Comment by Agusx1211** [comment]
There are two possible fixes for this issue:

a) Require imageHash != 0
b) Require threshold > 0

I think is best to implement the A fix because B also causes configurations with threshold of zero to become invalid, even when most of the time a threshold of zero is a bad idea, I still think is best if the wallet behaviour is mandated as much as possible by the configuration.

A wouldn't change any of that, because there is no possible configuration with imageHash of 0 (only no configuration), but there are possible configurations with threshold > 0, even when those configurations are just "anyone can make a transaction using this wallet".

**Comment by PhABC** [comment]
In favor of A) as well
