### ISSUE TITLE
QSP-2 Dangerous Self-Authorization and Delegate Call

### ISSUE THREAD

**Issue by Agusx1211** [arcadeum/wallet-contracts#63]
<img width="1472" alt="Screenshot 2020-06-08 at 12 25 15" src="https://user-images.githubusercontent.com/12701942/84020453-1cf74b00-a983-11ea-8a44-342f1fa1ae54.png">

**Comment by Agusx1211** [comment]
This is expected behaviour, wallets and signers should only sign `delegateCall: true` transactions if they 100% trust the destination of such call, this allows wallets to have extended functionality on the fly, without having to re-configure the wallet.

This design also builds upon the assumption that if an attacker controls enough signers to reach the wallet's threshold, it effectively controls the wallet not matter what's the upgradeability process for the wallet itself. Such attacker could drain the wallet by signing transactions that move the funds without making use of the delegateCall flag.

**Comment by Agusx1211** [comment]
Nevertheless, I think is a good idea to have this caveats well documented.

**Comment by PhABC** [comment]
Indeed, up to the user to inspect the transactions and make sure they are not making a dangerous calls, like how EOA need to make sure they are giving their token allowance to trusted contracts. Wallets can add warnings when user set a tx to be a delegateCall, among other checks.
