### ISSUE TITLE
QSP-10 Owner Signature Gas Limit Problems

### ISSUE THREAD

**Issue by Agusx1211** [arcadeum/wallet-contracts#71]
<img width="1478" alt="Screenshot 2020-06-08 at 12 30 43" src="https://user-images.githubusercontent.com/12701942/84020880-dfdf8880-a983-11ea-82a6-a8bc115d3988.png">

**Comment by PhABC** [comment]
This will be documented indeed, with consideration for opcode cost repricing as well.
