### ISSUE TITLE
QSP-14 Unused Experimental Encoder

### ISSUE THREAD

**Issue by Agusx1211** [arcadeum/wallet-contracts#75]
<img width="1466" alt="Screenshot 2020-06-08 at 12 32 51" src="https://user-images.githubusercontent.com/12701942/84021030-2c2ac880-a984-11ea-8d58-b0ac310cb1bc.png">

**Comment by PhABC** [comment]
ABIEncoderV2 is not considered experimental anymore as of Solc > 0.6, see 

https://github.com/ethereum/solidity/releases/tag/v0.6.0

> From this release on, ABIEncoderV2 is not considered experimental any more, but you still have to activate it through the pragma.
