### ISSUE TITLE
QSP-15 Limited isContract() Check

### ISSUE THREAD

**Issue by Agusx1211** [arcadeum/wallet-contracts#76]
<img width="1499" alt="Screenshot 2020-06-08 at 12 33 53" src="https://user-images.githubusercontent.com/12701942/84021108-511f3b80-a984-11ea-828a-9f8ec4bf975e.png">

**Comment by PhABC** [comment]
Users are not expected to deploy their own implementation, simply point to which already deployed implementation they want to use. We can add a comment on this in the documentations nonetheless in case some developers are interested in this feature.
