### ISSUE TITLE
QSP-16 Reverting on Errors

### ISSUE THREAD

**Issue by Agusx1211** [arcadeum/wallet-contracts#77]
<img width="1530" alt="Screenshot 2020-06-08 at 12 34 24" src="https://user-images.githubusercontent.com/12701942/84021170-64320b80-a984-11ea-8f4d-97012a7c2891.png">

**Comment by PhABC** [comment]
The problem with a tx reverting on error is that the nonce does not get incremented, which is also unlike the default behavior of ethereum transactions. Either way, there is a break from how regular Ethereum transaction works and we decided to use `revertOnError` to avoid double negation and make this functionality easier to understand. Clients and wallets can set this behavior to true by default by setting this boolean to true.
