### ISSUE TITLE
QSP-17 Multiple Inheritance

### ISSUE THREAD

**Issue by Agusx1211** [arcadeum/wallet-contracts#78]
<img width="1500" alt="Screenshot 2020-06-08 at 12 46 04" src="https://user-images.githubusercontent.com/12701942/84022090-07375500-a986-11ea-8b4c-80e8870a3fc7.png">

**Comment by PhABC** [comment]
Considering we have tests for this, it should be fine, but we will definitely add comments on this in the documentation.
