### ISSUE TITLE
QSP-18 Missing Hook Target Enforcement

### ISSUE THREAD

**Issue by Agusx1211** [arcadeum/wallet-contracts#79]
<img width="1488" alt="Screenshot 2020-06-08 at 12 46 33" src="https://user-images.githubusercontent.com/12701942/84022153-161e0780-a986-11ea-8cf4-c3d39addcd45.png">

**Comment by PhABC** [comment]
the fallback method is only called if the function signature is non existent in the contract's function lookup. In the case of onERC1155Received, this hook is declared [here](https://github.com/arcadeum/wallet-contracts/blob/master/contracts/modules/commons/ModuleHooks.sol#L69), hence it will be called if the function signature is for this method, without it being registered as a hook via the `addHook()` method.
