### ISSUE TITLE
QSP-19 Case Sensitivity of Addresses

### ISSUE THREAD

**Issue by Agusx1211** [arcadeum/wallet-contracts#80]
<img width="1465" alt="Screenshot 2020-06-08 at 12 47 16" src="https://user-images.githubusercontent.com/12701942/84022218-2fbf4f00-a986-11ea-8b23-62906d55b483.png">

**Comment by PhABC** [comment]
Shouldn't be an issue since the config are encoded before being hashed, converting all the data to byte array. Only a broken library could potentially have this issue.
